### ISSUE TITLE
DEBBASE_SSH / DEBBASE_TIMEZONE don't work?

### ISSUE THREAD

**Issue by kmptkp** [jgoerzen/docker-debian-base#4]
Building and running this Dockerfile:

```
FROM jgoerzen/debian-base-security:stretch 
ENV DEBBASE_SSH      enabled 
ENV DEBBASE_TIMEZONE true 
CMD ["/usr/local/bin/boot-debian-base"]
```

with:

```
docker build -t testimage01
docker run -it testimage01
```
 or

`docker run -it testimage01 /bin/bash`

doesn't result in the expected container with ssh and timezone enabled. The docker `docker run -it testimage01 /bin/bash` invocation works but the container has no ssh key configured anywhere, and any attempt to ssh into the ip of the container from the host results in `ssh: connect to host 172.17.0.2 port 22: Connection refused` (as expected if ssh is not running). 

The `docker run -it testimage01` invocation does generate keys but then hangs with:

```
run-parts: executing /usr/local/preinit/00-checkroot
Cleaning up; ignore errors here:
[FAIL] Cleaning up temporary files... /tmp /run /run/lock failed!
run-parts: executing /usr/local/preinit/00-setinit
run-parts: executing /usr/local/preinit/01-syslog
Sending syslog to Docker (config file /etc/syslog.conf.stdout)
run-parts: executing /usr/local/preinit/01-timezone
Setting container timezone to true
cp: cannot stat '/usr/share/zoneinfo/true': No such file or directory
run-parts: /usr/local/preinit/01-timezone exited with return code 1
run-parts: executing /usr/local/preinit/02-ssh-server
SSH server enabled; unset DEBBASE_SSH to disable
Generating SSH host keys...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76.)
debconf: falling back to frontend: Readline
Creating SSH2 RSA key; this may take some time ...
2048 SHA256:+Rsbd1h+dU6gK8cOoDu0HCaFkExRR3vRjw7lCAjFQiA root@c9231d9bcb8f (RSA)
Creating SSH2 ECDSA key; this may take some time ...
256 SHA256:uHGMe6SHC7mZ8Zm85FrUOSBqImxPUrAqWu0Kz2/j0i8 root@c9231d9bcb8f (ECDSA)
Creating SSH2 ED25519 key; this may take some time ...
256 SHA256:8kIv/oJ/jzthQQH9kRhdsdT0P+q7yuABJcANbRzXdXc root@c9231d9bcb8f (ED25519)
invoke-rc.d: could not determine current runlevel
```

What happens is that `/usr/local/bin/boot-debian-base` dies with the error above while executing `run-parts --verbose /usr/local/preinit` (presumably thanks to `set -e`). That error ultimately comes from `dpkg-reconfigure openssh-server`. 

The `boot-debian-base` thus never gets to `exec /sbin/init 100>&1 1>&-`. When I run `exec /sbin/init 100>&1 1>&-` manually inside the container, I get another hang: 

INIT: version 2.88 booting
[info] Using makefile-style concurrent boot in runlevel S.
INIT: Entering runlevel: 2
[info] Using makefile-style concurrent boot in runlevel 2.
Aug  7 11:13:47 d3cf64152566 syslogd (GNU inetutils 1.9.4): restart
[ ok ] Starting system log daemon: syslogd.
Aug  7 11:13:47 d3cf64152566 cron[272]: (CRON) INFO (pidfile fd = 3)
Aug  7 11:13:47 d3cf64152566 cron[277]: (CRON) STARTUP (fork ok)
Aug  7 11:13:47 d3cf64152566 cron[277]: (CRON) INFO (Running @reboot jobs)
Aug  7 11:13:47 d3cf64152566 anacron[279]: Anacron 2.3 started on 2018-08-07
Aug  7 11:13:47 d3cf64152566 anacron[279]: Will run job `cron.daily' in 5 min.
Aug  7 11:13:47 d3cf64152566 anacron[279]: Will run job `cron.weekly' in 10 min.
Aug  7 11:13:47 d3cf64152566 anacron[279]: Will run job `cron.monthly' in 15 min.
Aug  7 11:13:47 d3cf64152566 anacron[279]: Jobs will be executed sequentially
Aug  7 11:13:47 d3cf64152566 sshd[330]: Server listening on 0.0.0.0 port 22.
Aug  7 11:13:47 d3cf64152566 sshd[330]: Server listening on :: port 22.
[ ok ] Starting periodic command scheduler: cron.
[ ok ] Starting anac(h)ronistic cron: anacron.
[ ok ] Starting deferred execution scheduler: atd.
[ ok ] Starting OpenBSD Secure Shell server: sshd.
[ ok ] Starting MTA: exim4.
INIT: no more processes left in this runlevel

Host machine:

`Linux myhost 4.13.0-1-amd64 #1 SMP Debian 4.13.4-2 (2017-10-15) x86_64 GNU/Linux`

**Comment by jgoerzen** [comment]
Hi,

I was able to duplicate the issue with the Dockerfile you provided.  Upon removing the DEBBASE_TIMEZONE line, however, it worked fine.  `true` isn't a valid timezone.  You'd need to set to, for instance, something like `America/Chicago`.

This wasn't completely clear in the docs, so I have clarified it there.  Thanks for reporting.

- John
